server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    gzip on;

    location = /list.json {
        add_header Access-Control-Allow-Origin * always;
        add_header Cache-Control "no-store" always;
        default_type application/json;
        try_files /list.json =404;
    }

    location / {
        add_header Access-Control-Allow-Origin * always;
        try_files $uri $uri/ /index.html;
    }
}
